<div class="statement-document">
    <div class="statement-document-header"><div><span class="admin-eyebrow">Statement of account</span><h2>{{ $statement->reference }}</h2><p>{{ $statement->isPublished() ? 'Published' : 'Draft generated' }} {{ ($statement->issued_at ?: $statement->created_at)->format('F d, Y · g:i A') }}</p></div><span class="dashboard-status-pill {{ $statement->isPublished() ? 'is-success' : 'is-warning' }}">{{ $statement->isPublished() ? 'Published' : 'Draft' }}</span></div>
    <div class="statement-parties"><div><small>Merchant</small><strong>{{ $statement->partner?->restaurant_name ?? 'Unavailable' }}</strong><span>{{ $statement->partner?->registered_business_name }}</span><span>{{ $statement->partner?->address }}</span></div><div><small>Statement period</small><strong>{{ $statement->period_start?->format('M d, Y') }} – {{ $statement->period_end?->format('M d, Y') }}</strong><span>{{ number_format($statement->order_count) }} completed {{ Str::plural('order', $statement->order_count) }}</span></div></div>
    <div class="table-responsive"><table class="table dashboard-data-table statement-detail-table"><thead><tr><th>Completed</th><th>Order</th><th>Type</th><th>Status</th><th>Subtotal</th><th>Convenience</th><th>VAT</th><th>Delivery</th><th>Discount</th><th>Total</th><th>Commission</th><th>Merchant net</th></tr></thead><tbody>@foreach($statement->items as $item)<tr>
        <td>{{ $item->completed_at?->format('M d, Y') }}<small>{{ $item->completed_at?->format('g:i A') }}</small></td><td><strong>#{{ $item->order_number ?? $item->order_id }}</strong></td><td>{{ str($item->fulfillment_type ?: 'delivery')->replace('_', ' ')->title() }}</td><td><span class="dashboard-status-pill is-success">{{ $item->order_status }}</span></td><td>₱{{ number_format($item->subtotal_amount, 2) }}</td><td>₱{{ number_format($item->convenience_fee_amount, 2) }}</td><td>₱{{ number_format($item->vat_amount, 2) }}</td><td>₱{{ number_format($item->delivery_fee_amount, 2) }}</td><td>₱{{ number_format($item->discount_amount, 2) }}</td><td>₱{{ number_format($item->total_amount, 2) }}</td><td>₱{{ number_format($item->commission_amount, 2) }}</td><td><strong>₱{{ number_format($item->merchant_net_amount, 2) }}</strong></td>
    </tr>@endforeach</tbody><tfoot><tr><td colspan="4"><strong>Statement totals</strong></td><td>₱{{ number_format($statement->subtotal_amount, 2) }}</td><td>₱{{ number_format($statement->convenience_fee_amount, 2) }}</td><td>₱{{ number_format($statement->vat_amount, 2) }}</td><td>₱{{ number_format($statement->delivery_fee_amount, 2) }}</td><td>₱{{ number_format($statement->discount_amount, 2) }}</td><td>₱{{ number_format($statement->total_amount, 2) }}</td><td>₱{{ number_format($statement->commission_amount, 2) }}</td><td><strong>₱{{ number_format($statement->merchant_net_amount, 2) }}</strong></td></tr></tfoot></table></div>
    @if($statement->notes)<div class="statement-note"><strong>Note</strong><p>{{ $statement->notes }}</p></div>@endif
    <div class="statement-summary-grid"><div><small>Gross order total</small><strong>₱{{ number_format($statement->total_amount, 2) }}</strong></div><div><small>Less Pahatud commission</small><strong>− ₱{{ number_format($statement->commission_amount, 2) }}</strong></div><div class="is-net"><small>Merchant net amount</small><strong>₱{{ number_format($statement->merchant_net_amount, 2) }}</strong></div></div>
</div>
